// <auto-generated />
using System;
using LAKAPSAGAP.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LAKAPSAGAP.Services.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.Attachment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("isArchived")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("UserId");

                    b.ToTable("Attachments");

                    b.HasData(
                        new
                        {
                            Id = "ATT_001",
                            AddedById = "ACC_001",
                            DateCreated = new DateTime(2024, 11, 27, 23, 17, 12, 69, DateTimeKind.Local).AddTicks(1728),
                            DateUpdated = new DateTime(2024, 11, 27, 23, 17, 12, 69, DateTimeKind.Local).AddTicks(1741),
                            IsDeleted = false,
                            Url = "wwwroot\\attachments\\default_user_image.png",
                            UserId = "ACC_001",
                            isArchived = false
                        });
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isArchived")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("LastModifiedById");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.Floor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarehouseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("isArchived")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.Kit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KitType")
                        .HasColumnType("int");

                    b.Property<string>("LastModifiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isArchived")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("LastModifiedById");

                    b.ToTable("Kits");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.KitComponent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KitId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastModifiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("isArchived")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("ItemId");

                    b.HasIndex("KitId");

                    b.HasIndex("LastModifiedById");

                    b.ToTable("KitComponents");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.Rack", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FloorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isArchived")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("FloorId");

                    b.HasIndex("LastModifiedById");

                    b.ToTable("Racks");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.ReliefReceived", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateReceived")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReceivedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceivedFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReliefType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TruckPlateNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarehouseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("isArchived")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("WarehouseId");

                    b.ToTable("ReliefReceiveds");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.StockDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExpiry")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastModifiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("RackId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("isArchived")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("BatchNumber");

                    b.HasIndex("ItemId");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("RackId");

                    b.ToTable("StockDetails");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.StockItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FloorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UoMId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("isArchived")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FloorId");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("UoMId");

                    b.ToTable("StockItems");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.UoM", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isArchived")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("LastModifiedById");

                    b.ToTable("UoMs");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.UserAuth", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ab582b92-ad2b-4ab0-869f-da6aee960786",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "47da6430-ce6d-41e8-ab6e-c965c3e91b89",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d064dc97-e250-4011-a005-9598fdd8e916",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "1b87f66d-2873-4e47-9960-b36c1e544b93",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "17362e30-f6ab-4817-890c-7454c6854685",
                            Email = "head@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c53fdc0a-ae25-4c86-822e-9eae461809ab",
                            TwoFactorEnabled = false,
                            UserName = "head"
                        },
                        new
                        {
                            Id = "dcf7833c-4005-4bd2-a140-7a12d483a1e4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "86e58f47-f1c3-47e7-9754-055c2c67cfcb",
                            Email = "barangay@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1de62baa-b3ca-49dd-995d-7a4b1ee4bd48",
                            TwoFactorEnabled = false,
                            UserName = "barangay"
                        });
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.UserInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Barangay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserAuthId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("isArchived")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserAuthId");

                    b.ToTable("UserInfos");

                    b.HasData(
                        new
                        {
                            Id = "ACC_001",
                            AddedById = "ACC_001",
                            Barangay = "Karuhatan",
                            DateCreated = new DateTime(2024, 11, 27, 23, 17, 12, 69, DateTimeKind.Local).AddTicks(1773),
                            DateUpdated = new DateTime(2024, 11, 27, 23, 17, 12, 69, DateTimeKind.Local).AddTicks(1774),
                            Email = "admin@gmail.com",
                            FirstName = "LakapSagap",
                            IsDeleted = false,
                            LastName = "Admin",
                            MiddleName = "Capstone",
                            Phone = "09123456789",
                            RoleId = "8e7233fb-e64e-49d6-9213-6f193c251cf1",
                            UserAuthId = "ab582b92-ad2b-4ab0-869f-da6aee960786",
                            isArchived = false
                        });
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.Warehouse", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isArchived")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("LastModifiedById");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8e7233fb-e64e-49d6-9213-6f193c251cf1",
                            Name = "CSWD Administration Staff",
                            NormalizedName = "CSWD_ADMINISTRATION_STAFF"
                        },
                        new
                        {
                            Id = "6cf9062a-4e98-4928-8623-57fc76441007",
                            Name = "CSWD Office Head",
                            NormalizedName = "CSWD_OFFICE_HEAD"
                        },
                        new
                        {
                            Id = "084cb120-a5ad-4040-9781-23634203ac48",
                            Name = "Barangay Representative",
                            NormalizedName = "BARANGAY_REPRESENTATIVE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.Attachment", b =>
                {
                    b.HasOne("LAKAPSAGAP.Models.Models.UserInfo", "AddedBy")
                        .WithMany("AddedAttachments")
                        .HasForeignKey("AddedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LAKAPSAGAP.Models.Models.UserInfo", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById");

                    b.HasOne("LAKAPSAGAP.Models.Models.UserInfo", "User")
                        .WithMany("UserAttachments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AddedBy");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.Category", b =>
                {
                    b.HasOne("LAKAPSAGAP.Models.Models.UserInfo", "AddedBy")
                        .WithMany("CategoriesCreated")
                        .HasForeignKey("AddedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LAKAPSAGAP.Models.Models.UserInfo", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById");

                    b.Navigation("AddedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.Floor", b =>
                {
                    b.HasOne("LAKAPSAGAP.Models.Models.UserInfo", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("LAKAPSAGAP.Models.Models.UserInfo", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById");

                    b.HasOne("LAKAPSAGAP.Models.Models.Warehouse", "Warehouse")
                        .WithMany("FloorList")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AddedBy");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.Kit", b =>
                {
                    b.HasOne("LAKAPSAGAP.Models.Models.UserInfo", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("LAKAPSAGAP.Models.Models.UserInfo", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById");

                    b.Navigation("AddedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.KitComponent", b =>
                {
                    b.HasOne("LAKAPSAGAP.Models.Models.UserInfo", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("LAKAPSAGAP.Models.Models.StockItem", "StockItem")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LAKAPSAGAP.Models.Models.Kit", null)
                        .WithMany("KitComponentList")
                        .HasForeignKey("KitId");

                    b.HasOne("LAKAPSAGAP.Models.Models.UserInfo", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById");

                    b.Navigation("AddedBy");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("StockItem");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.Rack", b =>
                {
                    b.HasOne("LAKAPSAGAP.Models.Models.UserInfo", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("LAKAPSAGAP.Models.Models.Floor", "Floor")
                        .WithMany("Racks")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LAKAPSAGAP.Models.Models.UserInfo", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById");

                    b.Navigation("AddedBy");

                    b.Navigation("Floor");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.ReliefReceived", b =>
                {
                    b.HasOne("LAKAPSAGAP.Models.Models.UserInfo", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("LAKAPSAGAP.Models.Models.UserInfo", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById");

                    b.HasOne("LAKAPSAGAP.Models.Models.Warehouse", "Warehouse")
                        .WithMany("ReliefReceivedList")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AddedBy");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.StockDetail", b =>
                {
                    b.HasOne("LAKAPSAGAP.Models.Models.UserInfo", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("LAKAPSAGAP.Models.Models.ReliefReceived", "BatchDetail")
                        .WithMany("StockDetailList")
                        .HasForeignKey("BatchNumber")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LAKAPSAGAP.Models.Models.StockItem", "Item")
                        .WithMany("StockDetailList")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LAKAPSAGAP.Models.Models.UserInfo", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById");

                    b.HasOne("LAKAPSAGAP.Models.Models.Rack", "Rack")
                        .WithMany("StockDetailList")
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AddedBy");

                    b.Navigation("BatchDetail");

                    b.Navigation("Item");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("Rack");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.StockItem", b =>
                {
                    b.HasOne("LAKAPSAGAP.Models.Models.UserInfo", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("LAKAPSAGAP.Models.Models.Category", "Category")
                        .WithMany("StockItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LAKAPSAGAP.Models.Models.Floor", null)
                        .WithMany("StockItems")
                        .HasForeignKey("FloorId");

                    b.HasOne("LAKAPSAGAP.Models.Models.UserInfo", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById");

                    b.HasOne("LAKAPSAGAP.Models.Models.UoM", "UoM")
                        .WithMany("StockItems")
                        .HasForeignKey("UoMId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AddedBy");

                    b.Navigation("Category");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("UoM");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.UoM", b =>
                {
                    b.HasOne("LAKAPSAGAP.Models.Models.UserInfo", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("LAKAPSAGAP.Models.Models.UserInfo", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById");

                    b.Navigation("AddedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.UserInfo", b =>
                {
                    b.HasOne("LAKAPSAGAP.Models.Models.UserInfo", "AddedBy")
                        .WithMany("AddedUsers")
                        .HasForeignKey("AddedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LAKAPSAGAP.Models.Models.UserInfo", "LastModifiedBy")
                        .WithMany("LasModifiedByList")
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LAKAPSAGAP.Models.Models.UserAuth", "UserAuth")
                        .WithMany()
                        .HasForeignKey("UserAuthId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddedBy");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("Role");

                    b.Navigation("UserAuth");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.Warehouse", b =>
                {
                    b.HasOne("LAKAPSAGAP.Models.Models.UserInfo", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("LAKAPSAGAP.Models.Models.UserInfo", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById");

                    b.Navigation("AddedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LAKAPSAGAP.Models.Models.UserAuth", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LAKAPSAGAP.Models.Models.UserAuth", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LAKAPSAGAP.Models.Models.UserAuth", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LAKAPSAGAP.Models.Models.UserAuth", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.Category", b =>
                {
                    b.Navigation("StockItems");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.Floor", b =>
                {
                    b.Navigation("Racks");

                    b.Navigation("StockItems");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.Kit", b =>
                {
                    b.Navigation("KitComponentList");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.Rack", b =>
                {
                    b.Navigation("StockDetailList");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.ReliefReceived", b =>
                {
                    b.Navigation("StockDetailList");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.StockItem", b =>
                {
                    b.Navigation("StockDetailList");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.UoM", b =>
                {
                    b.Navigation("StockItems");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.UserInfo", b =>
                {
                    b.Navigation("AddedAttachments");

                    b.Navigation("AddedUsers");

                    b.Navigation("CategoriesCreated");

                    b.Navigation("LasModifiedByList");

                    b.Navigation("UserAttachments");
                });

            modelBuilder.Entity("LAKAPSAGAP.Models.Models.Warehouse", b =>
                {
                    b.Navigation("FloorList");

                    b.Navigation("ReliefReceivedList");
                });
#pragma warning restore 612, 618
        }
    }
}
